# Numpy Basics <hr style="border:3.5px solid #ff56bbff"></hr> 

<b>Marian Kristel M. Banquisio</b>
<br>BSECE-3A
<br>January 17, 2026

In [10]:
#%pip install numpy --upgrade
#%pip install scipy --upgrade

In [11]:
#%pip install --upgrade pip

In [12]:
# imports and packages
import numpy as np
from scipy import stats
from statistics import multimode

# 1D ARRAY <hr style="border: none; border-top: 1px dashed #ff56bb;width: 75%; margin: 10px 0;"></hr>

In [53]:
# 1-dimensional array
array_a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array_a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# size of an array
np.shape(array_a)

(9,)

In [23]:
array_b = np.array([11, 12, 13, 14, 15, 16, 17])
array_b

array([11, 12, 13, 14, 15, 16, 17])

# 2D ARRAY <hr style="border: none; border-top: 1px dashed #ff56bb;width: 75%; margin: 10px 0;"></hr>

In [33]:
# 2-dimensional array
my_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
#size of matrix
np.shape(my_array)

(2, 5)

In [38]:
#transpose of a matrix
t_array = my_array.T
t_array

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [41]:
#size of matrix
np.shape(t_array)

(5, 2)

# Measures of Central Tendency <hr style="border: none; border-top: 1px dashed #ff56bb;width: 75%; margin: 10px 0;"></hr>

In [ ]:

 # Jaguar vs. Panther
resistance = np.array([[10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
                       [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]])
resistance


array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [46]:
np.shape(resistance)

(2, 11)

In [47]:
resistance.T

array([[10.6, 10.1],
       [ 9.1, 11. ],
       [ 9.3,  9.1],
       [ 9.8, 20. ],
       [10.5,  9.2],
       [10.4, 10.8],
       [ 9.5,  9.9],
       [11. ,  9.2],
       [10.4,  9.1],
       [ 3. ,  9.1],
       [ 9.8,  nan]])

In [48]:
np.mean(resistance,axis=0)

array([10.35, 10.05,  9.2 , 14.9 ,  9.85, 10.6 ,  9.7 , 10.1 ,  9.75,
        6.05,   nan])

In [49]:
np.mean(resistance,axis=1)

array([9.4, nan])

In [51]:
# Mean
np.nanmean(resistance,axis=1)

array([ 9.4 , 10.75])

In [54]:
jaguar_mean = np.nanmean(resistance, axis=1)[0]
panther_mean = np.nanmean(resistance, axis=1)[1]

print(f'Jaguar Mean: {jaguar_mean: .2f} ohms')
print(f'Panther Mean: {panther_mean: .2f} ohms')

Jaguar Mean:  9.40 ohms
Panther Mean:  10.75 ohms


In [56]:
# Median
np.nanmedian(resistance, axis=1)

array([9.8 , 9.55])

In [57]:
jag_median = np.nanmedian(resistance, axis=1)[0]
pan_median = np.nanmedian(resistance, axis=1)[1]

print(f'Jaguar Median: {jag_median: .2f} ohms')
print(f'Panther Median: {pan_median: .2f} ohms')

Jaguar Median:  9.80 ohms
Panther Median:  9.55 ohms


In [58]:
# Mode
stats.mode(resistance, axis=1)

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [59]:
my_array = [1,1,2,2,3,4,5]
multimode(my_array)

[1, 2]

In [60]:
jag_res = resistance[0]

print("jaguar mode")
for i in multimode(jag_res):
    print(f'{i} ohms')

jaguar mode
9.8 ohms
10.4 ohms


In [61]:
pan_res = resistance[1]

print("panther mode")
for i in multimode(pan_res):
    print(f'{i} ohms')
    

panther mode
9.1 ohms


# Measures of Variability <hr style="border: none; border-top: 1px dashed #ff56bb;width: 75%; margin: 10px 0;"></hr>

In [63]:
# Jaguar vs. Panther
resistance = np.array([[10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
                       [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [64]:
# Range
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range


array([ 8. , 10.9])

In [65]:
print(f'Jaguar Range: {res_range[0]: .2f} ohms')
print(f'Panther Range: {res_range[1]: .2f} ohms')

Jaguar Range:  8.00 ohms
Panther Range:  10.90 ohms


In [66]:
# 1st Quartile
res_Q1 = np.nanpercentile(resistance, 25, axis=1)
res_Q1

array([9.4  , 9.125])

In [67]:
# 2nd Quartile
res_Q2 = np.nanpercentile(resistance, 50, axis=1)
res_Q2

array([9.8 , 9.55])

In [68]:
# 3rd Quartile
res_Q3 = np.nanpercentile(resistance, 75, axis=1)
res_Q3

array([10.45 , 10.625])

In [69]:
# IQR
print(f'Jaguar IQR: {res_Q3[0] - res_Q1[0]: .2f} ohms')
print(f'Panther IQR: {res_Q3[1] - res_Q1[1]: .2f} ohms')

Jaguar IQR:  1.05 ohms
Panther IQR:  1.50 ohms


In [71]:
# Variance
res_variance = np.nanvar(resistance,ddof=1, axis=1)
res_variance

array([ 4.86      , 11.08277778])

In [72]:
print(f'Jaguar Variance: {res_variance[0]: .2f} ohms')
print(f'Panther Variance: {res_variance[1]: .2f} ohms')

Jaguar Variance:  4.86 ohms
Panther Variance:  11.08 ohms


In [74]:
# Standard Deviation
res_std = np.nanstd(resistance,ddof=1, axis=1)
res_std

array([2.20454077, 3.32908062])

In [75]:
print(f'Jaguar Standard Deviation: {res_std[0]: .2f} ohms')
print(f'Panther Standard Deviation: {res_std[1]: .2f} ohms')

Jaguar Standard Deviation:  2.20 ohms
Panther Standard Deviation:  3.33 ohms
